apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
      - name: hello-go
        image: garvshah07/hello-go:latest
        ports:
        - containerPort: 8080


   